// export const questions = [
//   {
//     id: 1,
//     text: "What’s your age?",
//     type: "Single Select",
//     options: ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
//   },
//   {
//     id: 2,
//     text: "How often do you feel tired or lack energy, even after rest?",
//     type: "Single Select",
//     options: ["Often", "Sometimes", "Rarely"],
//   },
//   {
//     id: 3,
//     text: "Do you often leave things to the last minute?",
//     type: "Single Select",
//     options: ["Often", "Sometimes", "Never"],
//   },
//   {
//     id: 4,
//     text: "How easily distracted are you?",
//     type: "Single Select",
//     options: ["Easily distracted", "Occasionally lose focus", "Rarely lose focus", "Very focused"],
//   },
//   {
//     id: 5,
//     text: "How often do you feel worried or overwhelmed?",
//     type: "Single Select",
//     options: ["Often", "Sometimes", "Rarely"],
//   },
//   {
//     id: 6,
//     text: "How often do you experience mood swings?",
//     type: "Single Select",
//     options: ["Often", "Sometimes", "Rarely"],
//   },
//   {
//     id: 7,
//     text: "Have you felt in harmony with yourself and your circle in recent months?",
//     type: "Single Select",
//     options: ["Yes", "Moderately", "No"],
//   },
//   {
//     id: 8,
//     text: "It’s difficult for me to express emotions",
//     type: "Agreement Scale",
//     options: ["Strongly disagree", "Somewhat disagree", "Not sure", "Somewhat agree", "Strongly agree"],
//   },
//   {
//     id: 9,
//     text: "I often feel overwhelmed by the amount of tasks I have to do",
//     type: "Agreement Scale",
//     options: ["Strongly disagree", "Somewhat disagree", "Not sure", "Somewhat agree", "Strongly agree"],
//   },
//   {
//     id: 10,
//     text: "I often find it challenging to make a decision",
//     type: "Agreement Scale",
//     options: ["Strongly disagree", "Somewhat disagree", "Not sure", "Somewhat agree", "Strongly agree"],
//   },
//   {
//     id: 11,
//     text: "I often struggle to pursue my ambitions due to fear of messing up and failing",
//     type: "Agreement Scale",
//     options: ["Strongly disagree", "Somewhat disagree", "Not sure", "Somewhat agree", "Strongly agree"],
//   },
//   {
//     id: 12,
//     text: "Have you ever struggled with accepting compliments because you didn’t believe they are true?",
//     type: "Single Select",
//     options: ["Almost always", "Depends", "Not at all", "I’m not sure"],
//   },
//   {
//     id: 13,
//     text: "I tend to feel insecure while talking to others",
//     type: "Single Select",
//     options: ["Yes", "No", "I’m not sure"],
//   },
//   {
//     id: 14,
//     text: "I tend to overthink my partner’s behavior",
//     type: "Single Select",
//     options: ["Yes", "No", "I’m not sure"],
//   },
//   {
//     id: 15,
//     text: "Do you often prioritize others' needs and sacrifice your own ones?",
//     type: "Single Select",
//     options: ["Often", "Sometimes", "Never"],
//   },
//   {
//     id: 16,
//     text: "When was the last time you felt driven and motivated?",
//     type: "Single Select",
//     options: ["A few weeks ago", "Less than a year ago", "More than a year ago", "Never in my life"],
//   },
//   {
//     id: 17,
//     text: "Are there aspects of your well-being you'd like to address?",
//     type: "Multiple Select",
//     options: ["Low energy", "Worry", "Emotional exhaustion", "Overthinking", "Irritability", "I’m totally fine"],
//   },
//   {
//     id: 18,
//     text: "What do you usually do first thing in the morning?",
//     type: "Single Select",
//     options: ["Picking up my phone", "Making coffee", "Brushing teeth & taking shower", "Other"],
//   },
//   {
//     id: 19,
//     text: "How much time do you dedicate to physical activity each week?",
//     type: "Single Select",
//     options: ["0–2 hours", "3–5 hours", "6–8 hours", "More than 8 hours"],
//   },
//   {
//     id: 20,
//     text: "Do you have any habits that you’d like to quit?",
//     type: "Multiple Select",
//     options: ["Being late / running out of time", "Self-doubt", "Social media", "Sugar cravings or junk food", "Losing sleep", "Nail-biting", "Binge-watching"],
//   },
//   {
//     id: 21,
//     text: "Is there anything you want to improve about your sleep?",
//     type: "Multiple Select",
//     options: ["Waking up tired", "Waking up during the night", "Difficulty falling asleep", "Unstable sleep schedule", "I sleep well"],
//   },
//   {
//     id: 22,
//     text: "Have any of the following caused you to struggle more than before?",
//     type: "Multiple Select",
//     options: ["Family or relationship", "External circumstances", "My appearance", "Sleep issues", "Job-related stress", "Other"],
//   },
//   {
//     id: 23,
//     text: "In order to live a happier life, what do you think you need to improve?",
//     type: "Multiple Select",
//     options: ["My state of calm", "My focus levels", "My willpower", "My energy levels", "My inner resilience", "Other"],
//   },
//   {
//     id: 24,
//     text: "Which of the following would you like to start working on with your plan?",
//     type: "Multiple Select",
//     options: ["Stop doubting myself", "Build emotional resilience", "Set and achieve goals", "Stop overthinking", "Improve my ability to trust others", "Improve my daily routine"],
//   },
//   {
//     id: 25,
//     text: "How much do you know about behavioral techniques?",
//     type: "Single Select",
//     options: ["Nothing at all", "Not that much", "A lot"],
//   },
//   {
//     id: 26,
//     text: "Did you hear about Liven from an expert?",
//     type: "Single Select",
//     options: ["Yes", "No"],
//   },
//   {
//     id: 27,
//     text: "Set your daily goal",
//     type: "Single Select",
//     options: ["5 min/day", "10 min/day", "15 min/day", "20 min/day"],
//   },
// ];



export const questions = [
  {
    id: 1,
    text: "What’s your age?",
    description: "Helps us understand your life stage.",
    type: "Single Select",
    options: ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
  },
  {
    id: 2,
    text: "How often do you feel tired or lack energy, even after rest?",
    description: "Shows your usual energy level.",
    type: "Single Select",
    options: ["Often", "Sometimes", "Rarely"],
  },
  {
    id: 3,
    text: "Do you often leave things to the last minute?",
    description: "Helps understand how you manage tasks.",
    type: "Single Select",
    options: ["Often", "Sometimes", "Never"],
  },
  {
    id: 4,
    text: "How easily distracted are you?",
    description: "Measures your ability to stay focused.",
    type: "Single Select",
    options: [
      "Easily distracted",
      "Occasionally lose focus",
      "Rarely lose focus",
      "Very focused",
    ],
  },
  {
    id: 5,
    text: "How often do you feel worried or overwhelmed?",
    description: "Shows how frequently you feel stressed.",
    type: "Single Select",
    options: ["Often", "Sometimes", "Rarely"],
  },
  {
    id: 6,
    text: "How often do you experience mood swings?",
    description: "Helps assess emotional stability.",
    type: "Single Select",
    options: ["Often", "Sometimes", "Rarely"],
  },
  {
    id: 7,
    text: "Have you felt in harmony with yourself and your circle in recent months?",
    description: "Reflects your sense of balance and connection.",
    type: "Single Select",
    options: ["Yes", "Moderately", "No"],
  },
  {
    id: 8,
    text: "It’s difficult for me to express emotions",
    description: "Shows how comfortable you are sharing feelings.",
    type: "Agreement Scale",
    options: [
      "Strongly disagree",
      "Somewhat disagree",
      "Not sure",
      "Somewhat agree",
      "Strongly agree",
    ],
  },
  {
    id: 9,
    text: "I often feel overwhelmed by the amount of tasks I have to do",
    description: "Measures how workload affects you.",
    type: "Agreement Scale",
    options: [
      "Strongly disagree",
      "Somewhat disagree",
      "Not sure",
      "Somewhat agree",
      "Strongly agree",
    ],
  },
  {
    id: 10,
    text: "I often find it challenging to make a decision",
    description: "Shows how difficult decision-making feels.",
    type: "Agreement Scale",
    options: [
      "Strongly disagree",
      "Somewhat disagree",
      "Not sure",
      "Somewhat agree",
      "Strongly agree",
    ],
  },
  {
    id: 11,
    text: "I often struggle to pursue my ambitions due to fear of messing up and failing",
    description: "Reflects fear of failure affecting goals.",
    type: "Agreement Scale",
    options: [
      "Strongly disagree",
      "Somewhat disagree",
      "Not sure",
      "Somewhat agree",
      "Strongly agree",
    ],
  },
  {
    id: 12,
    text: "Have you ever struggled with accepting compliments because you didn’t believe they are true?",
    description: "Shows comfort with positive feedback.",
    type: "Single Select",
    options: ["Almost always", "Depends", "Not at all", "I’m not sure"],
  },
  {
    id: 13,
    text: "I tend to feel insecure while talking to others",
    description: "Measures confidence in social situations.",
    type: "Single Select",
    options: ["Yes", "No", "I’m not sure"],
  },
  {
    id: 14,
    text: "I tend to overthink my partner’s behavior",
    description: "Shows tendency to overthink relationships.",
    type: "Single Select",
    options: ["Yes", "No", "I’m not sure"],
  },
  {
    id: 15,
    text: "Do you often prioritize others' needs and sacrifice your own ones?",
    description: "Reflects how often you put yourself last.",
    type: "Single Select",
    options: ["Often", "Sometimes", "Never"],
  },
  {
    id: 16,
    text: "When was the last time you felt driven and motivated?",
    description: "Shows how recent your motivation was.",
    type: "Single Select",
    options: [
      "A few weeks ago",
      "Less than a year ago",
      "More than a year ago",
      "Never in my life",
    ],
  },
  {
    id: 17,
    text: "Are there aspects of your well-being you'd like to address?",
    description: "Highlights areas you want to improve.",
    type: "Multiple Select",
    options: [
      "Low energy",
      "Worry",
      "Emotional exhaustion",
      "Overthinking",
      "Irritability",
      "I’m totally fine",
    ],
  },
  {
    id: 18,
    text: "What do you usually do first thing in the morning?",
    description: "Gives insight into your daily routine.",
    type: "Single Select",
    options: [
      "Picking up my phone",
      "Making coffee",
      "Brushing teeth & taking shower",
      "Other",
    ],
  },
  {
    id: 19,
    text: "How much time do you dedicate to physical activity each week?",
    description: "Shows your activity level.",
    type: "Single Select",
    options: ["0–2 hours", "3–5 hours", "6–8 hours", "More than 8 hours"],
  },
  {
    id: 20,
    text: "Do you have any habits that you’d like to quit?",
    description: "Identifies habits you want to change.",
    type: "Multiple Select",
    options: [
      "Being late / running out of time",
      "Self-doubt",
      "Social media",
      "Sugar cravings or junk food",
      "Losing sleep",
      "Nail-biting",
      "Binge-watching",
    ],
  },
  {
    id: 21,
    text: "Is there anything you want to improve about your sleep?",
    description: "Shows possible sleep-related issues.",
    type: "Multiple Select",
    options: [
      "Waking up tired",
      "Waking up during the night",
      "Difficulty falling asleep",
      "Unstable sleep schedule",
      "I sleep well",
    ],
  },
  {
    id: 22,
    text: "Have any of the following caused you to struggle more than before?",
    description: "Identifies main sources of stress.",
    type: "Multiple Select",
    options: [
      "Family or relationship",
      "External circumstances",
      "My appearance",
      "Sleep issues",
      "Job-related stress",
      "Other",
    ],
  },
  {
    id: 23,
    text: "In order to live a happier life, what do you think you need to improve?",
    description: "Shows what you believe affects happiness.",
    type: "Multiple Select",
    options: [
      "My state of calm",
      "My focus levels",
      "My willpower",
      "My energy levels",
      "My inner resilience",
      "Other",
    ],
  },
  {
    id: 24,
    text: "Which of the following would you like to start working on with your plan?",
    description: "Defines your personal improvement goals.",
    type: "Multiple Select",
    options: [
      "Stop doubting myself",
      "Build emotional resilience",
      "Set and achieve goals",
      "Stop overthinking",
      "Improve my ability to trust others",
      "Improve my daily routine",
    ],
  },
  {
    id: 25,
    text: "How much do you know about behavioral techniques?",
    description: "Shows your level of prior knowledge.",
    type: "Single Select",
    options: ["Nothing at all", "Not that much", "A lot"],
  },
  {
    id: 26,
    text: "Did you hear about Liven from an expert?",
    description: "Helps understand how you found us.",
    type: "Single Select",
    options: ["Yes", "No"],
  },
  {
    id: 27,
    text: "Set your daily goal",
    description: "Sets how much time you want to invest daily.",
    type: "Single Select",
    options: ["5 min/day", "10 min/day", "15 min/day", "20 min/day"],
  },
];
